CREATE TABLE `BOARD` (
  `BOARDNO` int(11) NOT NULL AUTO_INCREMENT COMMENT '고유번호',
  `TITLE` varchar(100) NOT NULL COMMENT '제목',
  `CONTENTS` text NOT NULL COMMENT '내용',
  `ID` varchar(50) DEFAULT NULL,
  `NAME` varchar(30) NOT NULL,
  `PASSWORD` varchar(20) NOT NULL,
  `REGDATE` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '작성시간',
  `LAST_UPDATE_DATE` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  PRIMARY KEY (`BOARDNO`),
  UNIQUE KEY `BOARDNO` (`BOARDNO`)
) ENGINE=MyISAM AUTO_INCREMENT=179 DEFAULT CHARSET=utf8 COMMENT='게시판';

